<?php
/**
 * @file
 */


/**
 * wysiwyg_editor_settings_alter() - define custom styles for the wysiwyg editor
 */
function setup_wysiwyg_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->editor == 'ckeditor') {
    $settings['stylesCombo_stylesSet'] = 'setup_wysiwyg_styles:' . base_path() . drupal_get_path('module', 'setup_wysiwyg').'/wysiwyg_styles.js';
//        dpm($settings);
  }
}
