<?php
/**
 * @file
 */


/**
 * wysiwyg_editor_settings_alter() - define custom styles for the wysiwyg editor
 */
function wysiwyg_setup_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->editor == 'ckeditor') {
    $settings['stylesCombo_stylesSet'] = 'wysiwyg_setup_styles:' . base_path() . drupal_get_path('module', 'wysiwyg_setup').'/wysiwyg_styles.js';
//        dpm($settings);
  }
}
